# CMakeList.txt : CMake project for Battleship Test 1Make, include source and define
# project specific logic here.
#

# Add source to this project's executable.
add_executable (BTestMake "Battleship Test 1Make.cpp" "Battleship Test 1Make.h" "Helper.h" "UserInput.cpp" "UserInput.h" "FileFuncs.cpp" "FileFuncs.h" Helper.cpp)

if (CMAKE_VERSION VERSION_GREATER 3.12)
  set_property(TARGET BTestMake PROPERTY CXX_STANDARD 20)
endif()

# TODO: Add tests and install targets if needed.
